# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f793463b20d542fdd192d7600fe7fdcb1bc5a861ffae7cc3e4ff70dc2afd5c98838d3c0cf11300977987a08bc74ff640363ed9c03ea90ddec3d1dca11650cfa0

test:
  secret_key_base: bb250f7d3a1289c0b8622bd46b8c9946edfff2bb5e4fc7eb69af26b8373107135182a40816c0f98fb6544d6be4a4cc02ff9d6cd26152d2be4e3b7f8dcdf8c020

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
